name: Release Pipeline

on:
  push:
    tags:
      - ui-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Release application
        run: echo "Releasing UI application"
